name: Docker Compose CI/CD

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and push Docker images
      - name: Build and Push Frontend Image
        run: |
          docker build -t josuecaztro/frontend:latest -f front-End/Dockerfile front-End
          docker push josuecaztro/frontend:latest

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Backend JAR
        run: |
          cd ivdd-backend
          mvn clean package -DskipTests

      - name: Build and Push Backend Image
        run: |
          docker build -t josuecaztro/backend:latest -f ivdd-backend/Dockerfile ivdd-backend
          docker push josuecaztro/backend:latest

      - name: Create SSH Key
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ec2-key.pem
          chmod 600 ec2-key.pem

      # Step 5: Deploy to your server
      - name: Deploy Containers to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2-key.pem ubuntu@iglesiavozdedios.net << 'EOF'
            cd /home/ubuntu/IVDD-Final-Website
            docker pull josuecaztro/frontend:latest
            docker pull josuecaztro/backend:latest
            docker-compose down
            docker-compose up -d --build
          EOF

